# Generated by Django 5.0.7 on 2024-09-12 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='genero',
            new_name='generos',
        ),
        migrations.AlterField(
            model_name='filmes',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genero'),
        ),
    ]
