# Generated by Django 5.0.7 on 2024-09-13 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_generos_genero_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classif', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='filmes',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='capa/'),
        ),
        migrations.AddField(
            model_name='filmes',
            name='urlImage',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmes',
            name='classif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classif'),
        ),
    ]
