# Generated by Django 5.0.7 on 2024-09-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_classif_filmes_imagem_filmes_urlimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='capa/')),
            ],
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='imagem',
        ),
    ]
