# Generated by Django 5.0.7 on 2024-09-20 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_imagem_remove_filmes_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='imagem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.imagem'),
            preserve_default=False,
        ),
    ]
